// <auto-generated />
using System;
using ITask7.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITask7.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302195214_Current2")]
    partial class Current2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("inventories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Track laptops, monitors, peripherals, and other IT assets",
                            IsPublic = false,
                            Name = "IT Equipment",
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 2, 25, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Track stationery, printer supplies, and office consumables",
                            IsPublic = true,
                            Name = "Office Supplies",
                            UpdatedAt = new DateTime(2026, 2, 25, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 2, 20, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Company vehicles and maintenance records",
                            IsPublic = false,
                            Name = "Vehicle Fleet",
                            UpdatedAt = new DateTime(2026, 2, 20, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086)
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryAccess", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("inventories_accesses", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DisplayInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId", "Name")
                        .IsUnique();

                    b.HasIndex("InventoryId", "SortOrder");

                    b.ToTable("inventory_fields", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Physical asset tag number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "asset_tag",
                            SortOrder = 1,
                            Title = "Asset Tag"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Manufacturer serial number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "serial_number",
                            SortOrder = 2,
                            Title = "Serial Number"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Original purchase price in USD",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "purchase_price",
                            SortOrder = 3,
                            Title = "Purchase Price"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Warranty expiration date",
                            DisplayInTable = false,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "warranty_expires",
                            SortOrder = 4,
                            Title = "Warranty Expires"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Currently assigned to employee",
                            DisplayInTable = true,
                            FieldType = "Boolean",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "is_assigned",
                            SortOrder = 5,
                            Title = "Assigned"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Additional information",
                            DisplayInTable = false,
                            FieldType = "MultiLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "notes",
                            SortOrder = 6,
                            Title = "Notes"
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Upload purchase documentation",
                            DisplayInTable = false,
                            FieldType = "Document",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "receipt",
                            SortOrder = 7,
                            Title = "Purchase Receipt"
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Name of the supply item",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "product_name",
                            SortOrder = 1,
                            Title = "Product Name"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Current stock count",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "quantity",
                            SortOrder = 2,
                            Title = "Quantity in Stock"
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Minimum stock before reorder",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "reorder_point",
                            SortOrder = 3,
                            Title = "Reorder Point"
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Supplier contact and ordering details",
                            DisplayInTable = false,
                            FieldType = "MultiLine",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = false,
                            Name = "supplier_info",
                            SortOrder = 4,
                            Title = "Supplier Information"
                        },
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Vehicle registration number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "license_plate",
                            SortOrder = 1,
                            Title = "License Plate"
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Odometer reading",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "mileage",
                            SortOrder = 2,
                            Title = "Current Mileage"
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Current insurance status",
                            DisplayInTable = true,
                            FieldType = "Boolean",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "insurance_active",
                            SortOrder = 3,
                            Title = "Insurance Active"
                        },
                        new
                        {
                            Id = new Guid("e4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            Description = "Annual inspection reports",
                            DisplayInTable = false,
                            FieldType = "Document",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = false,
                            Name = "inspection_docs",
                            SortOrder = 4,
                            Title = "Inspection Documents"
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CustomId")
                        .IsUnique();

                    b.HasIndex("InventoryId");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-LAPTOP-001",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 17, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-LAPTOP-002",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 2, 17, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086)
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 1, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-MON-001",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 1, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086)
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 27, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "SUP-A4-PAPER",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UpdatedAt = new DateTime(2026, 3, 1, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086)
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 2, 26, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "SUP-TONER-BLK",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UpdatedAt = new DateTime(2026, 2, 28, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086)
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 23, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "VH-001",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UpdatedAt = new DateTime(2026, 3, 2, 14, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086)
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.ItemFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("boolean");

                    b.Property<string>("ValueDocumentUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValueNumeric")
                        .HasColumnType("numeric");

                    b.Property<string>("ValueText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("ItemId", "FieldId")
                        .IsUnique();

                    b.ToTable("item_field_values", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f58ceadc-9686-4fdc-b412-ed2db4d4e2e3"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "AST-2024-001"
                        },
                        new
                        {
                            Id = new Guid("b81eabd6-6c89-4f9f-a93f-1dfbcfc8ec9e"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "SN123456789"
                        },
                        new
                        {
                            Id = new Guid("90d8054e-0f8e-45fd-9505-25242c25d018"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueNumeric = 1299.99m
                        },
                        new
                        {
                            Id = new Guid("6a111047-ad38-4ee6-8fcf-c25131451375"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "2027-03-15"
                        },
                        new
                        {
                            Id = new Guid("d2dfac9b-e574-4048-b2ef-ce524fe17cfd"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("1a0e5a95-968f-440d-9a19-b146421961ba"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "Assigned to Engineering team lead"
                        },
                        new
                        {
                            Id = new Guid("8dedd63f-fb5a-4363-afd5-064a0f7d7c79"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "AST-2024-002"
                        },
                        new
                        {
                            Id = new Guid("e232550f-983e-488a-be32-79ec8d4a640a"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "SN987654321"
                        },
                        new
                        {
                            Id = new Guid("ff362eed-aaa3-45cb-9403-da426c93d077"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueNumeric = 1599.50m
                        },
                        new
                        {
                            Id = new Guid("575f61d8-11c1-49bd-a272-dcbc91cb1a32"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "2027-06-20"
                        },
                        new
                        {
                            Id = new Guid("98ec1452-5ea0-4ba7-b03d-c21f07398f40"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueBoolean = false
                        },
                        new
                        {
                            Id = new Guid("2688b07b-680c-4a3d-b917-3fd3fad0b399"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "AST-2023-045"
                        },
                        new
                        {
                            Id = new Guid("ec8017a0-9ee0-46e8-9a4b-434a971a0aab"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "DELL-SN-778899"
                        },
                        new
                        {
                            Id = new Guid("42d24187-094d-437e-b6fd-a249df0fd295"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueNumeric = 349.00m
                        },
                        new
                        {
                            Id = new Guid("0743ff03-788e-45a5-a5ed-363ea73dba07"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("d89c332e-e48b-43b5-888c-438e7d77e00f"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "A4 Copy Paper (500 sheets)"
                        },
                        new
                        {
                            Id = new Guid("6e0b18fd-bdc0-494e-ba85-2b3f24e4e534"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 1, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueNumeric = 45m
                        },
                        new
                        {
                            Id = new Guid("9692739f-0938-44d4-b377-5840f8ee3239"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueNumeric = 10m
                        },
                        new
                        {
                            Id = new Guid("5387e01e-dbbc-48ac-8c86-8e2e391a19d4"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "Staples Inc. - staples.com - Account #12345"
                        },
                        new
                        {
                            Id = new Guid("2fc24ade-281e-4f82-a47b-24970fa0c39a"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "HP LaserJet Black Toner 85A"
                        },
                        new
                        {
                            Id = new Guid("75732db6-171a-456f-b749-1060d38beac5"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 2, 28, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueNumeric = 3m
                        },
                        new
                        {
                            Id = new Guid("6a734c82-5ff3-4628-bede-a6b8192c8743"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueNumeric = 2m
                        },
                        new
                        {
                            Id = new Guid("3b61703d-85b9-417e-8a67-5ab521f58e9e"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("e1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueText = "ABC-1234"
                        },
                        new
                        {
                            Id = new Guid("b8ea6a26-b6e4-4e41-bd40-0c0775f310a2"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("e2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 14, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueNumeric = 45230m
                        },
                        new
                        {
                            Id = new Guid("4702bc73-76a2-4c2e-9c69-262a2d19fcc2"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("e3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("323cccba-ef93-45be-9f5b-5174a76367b2"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            FieldId = new Guid("e4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 52, 13, 133, DateTimeKind.Utc).AddTicks(4086),
                            ValueDocumentUrl = "/docs/inspections/van-2024.pdf"
                        });
                });

            modelBuilder.Entity("ITask7.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2f6c6266-6c5b-4b93-82d0-faee1d039008",
                            Email = "admin@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@COMPANY.COM",
                            NormalizedUserName = "ADMIN@COMPANY.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0118ffa2-c199-4f5f-bda5-d2fd4ae7cf15",
                            TwoFactorEnabled = false,
                            UserName = "admin@company.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", "Creator")
                        .WithMany("CreatedInventories")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryAccess", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Accesses")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITask7.Users.ApplicationUser", "User")
                        .WithMany("Accesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Fields")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.ItemFieldValue", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.InventoryField", "Field")
                        .WithMany("Values")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITask7.Models.Inventories.Item", "Item")
                        .WithMany("FieldValues")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("Fields");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("ITask7.Users.ApplicationUser", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("CreatedInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
