// <auto-generated />
using System;
using ITask7.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITask7.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302125305_NullableInventoryCreator")]
    partial class NullableInventoryCreator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("inventories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Track laptops, monitors, peripherals, and other IT assets",
                            Name = "IT Equipment",
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 2, 25, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Track stationery, printer supplies, and office consumables",
                            Name = "Office Supplies",
                            UpdatedAt = new DateTime(2026, 2, 25, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 2, 20, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Company vehicles and maintenance records",
                            Name = "Vehicle Fleet",
                            UpdatedAt = new DateTime(2026, 2, 20, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332)
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DisplayInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId", "Name")
                        .IsUnique();

                    b.HasIndex("InventoryId", "SortOrder");

                    b.ToTable("inventory_fields", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Physical asset tag number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "asset_tag",
                            SortOrder = 1,
                            Title = "Asset Tag"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Manufacturer serial number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "serial_number",
                            SortOrder = 2,
                            Title = "Serial Number"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Original purchase price in USD",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "purchase_price",
                            SortOrder = 3,
                            Title = "Purchase Price"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Warranty expiration date",
                            DisplayInTable = false,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "warranty_expires",
                            SortOrder = 4,
                            Title = "Warranty Expires"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Currently assigned to employee",
                            DisplayInTable = true,
                            FieldType = "Boolean",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "is_assigned",
                            SortOrder = 5,
                            Title = "Assigned"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Additional information",
                            DisplayInTable = false,
                            FieldType = "MultiLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "notes",
                            SortOrder = 6,
                            Title = "Notes"
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Upload purchase documentation",
                            DisplayInTable = false,
                            FieldType = "Document",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "receipt",
                            SortOrder = 7,
                            Title = "Purchase Receipt"
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Name of the supply item",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "product_name",
                            SortOrder = 1,
                            Title = "Product Name"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Current stock count",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "quantity",
                            SortOrder = 2,
                            Title = "Quantity in Stock"
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Minimum stock before reorder",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "reorder_point",
                            SortOrder = 3,
                            Title = "Reorder Point"
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Supplier contact and ordering details",
                            DisplayInTable = false,
                            FieldType = "MultiLine",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = false,
                            Name = "supplier_info",
                            SortOrder = 4,
                            Title = "Supplier Information"
                        },
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Vehicle registration number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "license_plate",
                            SortOrder = 1,
                            Title = "License Plate"
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Odometer reading",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "mileage",
                            SortOrder = 2,
                            Title = "Current Mileage"
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Current insurance status",
                            DisplayInTable = true,
                            FieldType = "Boolean",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "insurance_active",
                            SortOrder = 3,
                            Title = "Insurance Active"
                        },
                        new
                        {
                            Id = new Guid("e4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            Description = "Annual inspection reports",
                            DisplayInTable = false,
                            FieldType = "Document",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = false,
                            Name = "inspection_docs",
                            SortOrder = 4,
                            Title = "Inspection Documents"
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CustomId")
                        .IsUnique();

                    b.HasIndex("InventoryId");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-LAPTOP-001",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 10, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-LAPTOP-002",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 2, 10, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332)
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 1, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-MON-001",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 1, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332)
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 27, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "SUP-A4-PAPER",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UpdatedAt = new DateTime(2026, 3, 1, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332)
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 2, 26, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "SUP-TONER-BLK",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UpdatedAt = new DateTime(2026, 2, 28, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332)
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 23, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "VH-001",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UpdatedAt = new DateTime(2026, 3, 2, 7, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332)
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.ItemFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("boolean");

                    b.Property<string>("ValueDocumentUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValueNumeric")
                        .HasColumnType("numeric");

                    b.Property<string>("ValueText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("ItemId", "FieldId")
                        .IsUnique();

                    b.ToTable("item_field_values", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fab72190-d46b-4cd5-a443-c9cbd68708ed"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "AST-2024-001"
                        },
                        new
                        {
                            Id = new Guid("7cfca272-f8dc-4158-8326-dd40491c1d42"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "SN123456789"
                        },
                        new
                        {
                            Id = new Guid("3b404075-a7d6-42de-99f1-0e0b3049c5a5"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueNumeric = 1299.99m
                        },
                        new
                        {
                            Id = new Guid("a1c64120-f527-464a-80d6-06330aaf9c37"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "2027-03-15"
                        },
                        new
                        {
                            Id = new Guid("ca4ee84a-db1c-4dd9-9e5b-66fff6b9bbe8"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("24a31199-1fee-4169-817e-769a02b3ad95"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "Assigned to Engineering team lead"
                        },
                        new
                        {
                            Id = new Guid("7509da18-a6b1-4f2b-9ff5-d9c64b95bbbd"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "AST-2024-002"
                        },
                        new
                        {
                            Id = new Guid("6d38ddab-4e39-48cb-bfb8-d98ebef55216"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "SN987654321"
                        },
                        new
                        {
                            Id = new Guid("2beb8618-6639-438e-b2e9-f338727a6cc8"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueNumeric = 1599.50m
                        },
                        new
                        {
                            Id = new Guid("3ca02a68-3be0-42be-b5c9-965ce61ad667"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "2027-06-20"
                        },
                        new
                        {
                            Id = new Guid("4ff04b58-3d2b-4dd8-b361-3a48bf02dfe3"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueBoolean = false
                        },
                        new
                        {
                            Id = new Guid("040b8f0e-6f4a-40f3-ad67-a4ca470ab7f1"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "AST-2023-045"
                        },
                        new
                        {
                            Id = new Guid("321b71f2-9350-4c67-a2c9-c9cbf1e78595"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "DELL-SN-778899"
                        },
                        new
                        {
                            Id = new Guid("7d385fdd-5dff-4c16-b296-ee44732858b2"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueNumeric = 349.00m
                        },
                        new
                        {
                            Id = new Guid("67919566-fb0f-4af8-98d8-01a63967ef30"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("8ae8cf58-42ec-43a9-ad46-aa4eb1019e3a"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "A4 Copy Paper (500 sheets)"
                        },
                        new
                        {
                            Id = new Guid("794a94a5-fb97-40c8-b474-5177f2873e4a"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 1, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueNumeric = 45m
                        },
                        new
                        {
                            Id = new Guid("6d507067-8c0f-4d29-aed1-f8fa14e00c14"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueNumeric = 10m
                        },
                        new
                        {
                            Id = new Guid("c7e538eb-fa83-47a5-8531-cbc87bb1b40c"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "Staples Inc. - staples.com - Account #12345"
                        },
                        new
                        {
                            Id = new Guid("c800e8ea-237a-4710-a696-90b3b2648aed"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "HP LaserJet Black Toner 85A"
                        },
                        new
                        {
                            Id = new Guid("04d3775c-ac6d-4993-ac39-4a1d561e412e"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 2, 28, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueNumeric = 3m
                        },
                        new
                        {
                            Id = new Guid("d90b3e6d-8a0f-401d-a76c-f23e43653b1c"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueNumeric = 2m
                        },
                        new
                        {
                            Id = new Guid("e7355608-f784-4dac-9efe-ae615a887fdb"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("e1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueText = "ABC-1234"
                        },
                        new
                        {
                            Id = new Guid("3df43404-d116-4c83-a59f-fb0b9210e12e"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("e2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 7, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueNumeric = 45230m
                        },
                        new
                        {
                            Id = new Guid("cc6ffb49-9ca7-4f6e-9c9c-66df1e501211"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("e3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("41bfaf5c-a4bd-4f87-a1b4-1c8fc1965aea"),
                            CreatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            FieldId = new Guid("e4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 12, 53, 5, 96, DateTimeKind.Utc).AddTicks(4332),
                            ValueDocumentUrl = "/docs/inspections/van-2024.pdf"
                        });
                });

            modelBuilder.Entity("ITask7.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "898b0fb2-5ba5-40f2-988d-4128ad6fb60a",
                            Email = "admin@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@COMPANY.COM",
                            NormalizedUserName = "ADMIN@COMPANY.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b2b85423-7b4e-49f4-9975-ef235f365243",
                            TwoFactorEnabled = false,
                            UserName = "admin@company.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", "Creator")
                        .WithMany("CreatedInventories")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Fields")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.ItemFieldValue", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.InventoryField", "Field")
                        .WithMany("Values")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITask7.Models.Inventories.Item", "Item")
                        .WithMany("FieldValues")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("ITask7.Users.ApplicationUser", b =>
                {
                    b.Navigation("CreatedInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
