// <auto-generated />
using System;
using ITask7.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITask7.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302194322_Current")]
    partial class Current
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("inventories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Track laptops, monitors, peripherals, and other IT assets",
                            IsPublic = false,
                            Name = "IT Equipment",
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 2, 25, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Track stationery, printer supplies, and office consumables",
                            IsPublic = false,
                            Name = "Office Supplies",
                            UpdatedAt = new DateTime(2026, 2, 25, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 2, 20, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Company vehicles and maintenance records",
                            IsPublic = false,
                            Name = "Vehicle Fleet",
                            UpdatedAt = new DateTime(2026, 2, 20, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198)
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryAccess", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("inventories_accesses", (string)null);
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DisplayInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId", "Name")
                        .IsUnique();

                    b.HasIndex("InventoryId", "SortOrder");

                    b.ToTable("inventory_fields", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Physical asset tag number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "asset_tag",
                            SortOrder = 1,
                            Title = "Asset Tag"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Manufacturer serial number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "serial_number",
                            SortOrder = 2,
                            Title = "Serial Number"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Original purchase price in USD",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "purchase_price",
                            SortOrder = 3,
                            Title = "Purchase Price"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Warranty expiration date",
                            DisplayInTable = false,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "warranty_expires",
                            SortOrder = 4,
                            Title = "Warranty Expires"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Currently assigned to employee",
                            DisplayInTable = true,
                            FieldType = "Boolean",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "is_assigned",
                            SortOrder = 5,
                            Title = "Assigned"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Additional information",
                            DisplayInTable = false,
                            FieldType = "MultiLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "notes",
                            SortOrder = 6,
                            Title = "Notes"
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Upload purchase documentation",
                            DisplayInTable = false,
                            FieldType = "Document",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "receipt",
                            SortOrder = 7,
                            Title = "Purchase Receipt"
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Name of the supply item",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "product_name",
                            SortOrder = 1,
                            Title = "Product Name"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Current stock count",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "quantity",
                            SortOrder = 2,
                            Title = "Quantity in Stock"
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Minimum stock before reorder",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "reorder_point",
                            SortOrder = 3,
                            Title = "Reorder Point"
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Supplier contact and ordering details",
                            DisplayInTable = false,
                            FieldType = "MultiLine",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = false,
                            Name = "supplier_info",
                            SortOrder = 4,
                            Title = "Supplier Information"
                        },
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Vehicle registration number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "license_plate",
                            SortOrder = 1,
                            Title = "License Plate"
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Odometer reading",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "mileage",
                            SortOrder = 2,
                            Title = "Current Mileage"
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Current insurance status",
                            DisplayInTable = true,
                            FieldType = "Boolean",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "insurance_active",
                            SortOrder = 3,
                            Title = "Insurance Active"
                        },
                        new
                        {
                            Id = new Guid("e4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Annual inspection reports",
                            DisplayInTable = false,
                            FieldType = "Document",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = false,
                            Name = "inspection_docs",
                            SortOrder = 4,
                            Title = "Inspection Documents"
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CustomId")
                        .IsUnique();

                    b.HasIndex("InventoryId");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-LAPTOP-001",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 2, 17, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-LAPTOP-002",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 2, 17, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198)
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 1, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-MON-001",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 1, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198)
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 27, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "SUP-A4-PAPER",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UpdatedAt = new DateTime(2026, 3, 1, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198)
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 2, 26, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "SUP-TONER-BLK",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UpdatedAt = new DateTime(2026, 2, 28, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198)
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 23, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "VH-001",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UpdatedAt = new DateTime(2026, 3, 2, 14, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198)
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.ItemFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("boolean");

                    b.Property<string>("ValueDocumentUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValueNumeric")
                        .HasColumnType("numeric");

                    b.Property<string>("ValueText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("ItemId", "FieldId")
                        .IsUnique();

                    b.ToTable("item_field_values", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("18d61117-07b7-46a8-bd61-a2433533550e"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "AST-2024-001"
                        },
                        new
                        {
                            Id = new Guid("03e1af4a-e747-49c5-bd41-21921fcae76e"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "SN123456789"
                        },
                        new
                        {
                            Id = new Guid("24845f7d-2a50-4ae7-be6d-66627aec2c5b"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueNumeric = 1299.99m
                        },
                        new
                        {
                            Id = new Guid("87e88b53-0ce7-45a0-a46a-c2690c10b46d"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "2027-03-15"
                        },
                        new
                        {
                            Id = new Guid("615a386b-9b31-4d6c-b7ec-13f583d3dab6"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("5f42a60d-5a01-4a0d-b604-d3d0a9394af6"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "Assigned to Engineering team lead"
                        },
                        new
                        {
                            Id = new Guid("428d9378-cfa7-435a-a9ed-34ee2563c9f5"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "AST-2024-002"
                        },
                        new
                        {
                            Id = new Guid("1dce9092-e108-4720-ba51-fd30250317f0"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "SN987654321"
                        },
                        new
                        {
                            Id = new Guid("831ed8b4-2f3c-427e-94df-df058e44443d"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueNumeric = 1599.50m
                        },
                        new
                        {
                            Id = new Guid("622b849f-a9ab-4871-8c03-bd424db09f4a"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "2027-06-20"
                        },
                        new
                        {
                            Id = new Guid("1efe8d79-cec2-4fff-8498-28a525cfaf96"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueBoolean = false
                        },
                        new
                        {
                            Id = new Guid("187f4b82-8adb-4079-b9dc-a5e9fcabe3cd"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "AST-2023-045"
                        },
                        new
                        {
                            Id = new Guid("5e829980-3c57-44a1-8fb8-c245bf7e5bb5"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "DELL-SN-778899"
                        },
                        new
                        {
                            Id = new Guid("66ad5337-a3e0-4d79-a924-0bebde202ad9"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueNumeric = 349.00m
                        },
                        new
                        {
                            Id = new Guid("48e60de2-698a-44ff-8793-4c58279aad48"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("c483168c-b50e-4b1c-a616-fd4f86d62474"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "A4 Copy Paper (500 sheets)"
                        },
                        new
                        {
                            Id = new Guid("fbfc2126-6b16-4880-a925-179deffc7589"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 1, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueNumeric = 45m
                        },
                        new
                        {
                            Id = new Guid("620468dd-a6fe-4351-bf85-41fe052581b8"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueNumeric = 10m
                        },
                        new
                        {
                            Id = new Guid("46a496e2-852b-4571-b15c-a8c072694c19"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "Staples Inc. - staples.com - Account #12345"
                        },
                        new
                        {
                            Id = new Guid("6c789b79-9a16-4f26-946e-1e3608ec91b6"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "HP LaserJet Black Toner 85A"
                        },
                        new
                        {
                            Id = new Guid("e622eb36-d6ba-4a7c-9a2d-0aa34d059720"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 2, 28, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueNumeric = 3m
                        },
                        new
                        {
                            Id = new Guid("2885c2cb-001d-4c9c-9a3b-d5bde6cc56d2"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueNumeric = 2m
                        },
                        new
                        {
                            Id = new Guid("4f7c7238-de58-41a9-b0ac-4af1bfbaac4c"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("e1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueText = "ABC-1234"
                        },
                        new
                        {
                            Id = new Guid("1c4b97bf-7a13-495a-bcd7-6cdd1b6bfd68"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("e2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 14, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueNumeric = 45230m
                        },
                        new
                        {
                            Id = new Guid("5bfb3345-4e3f-474c-a35e-ebe71db68346"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("e3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("643ad983-6f65-4247-bf32-6a661546bfb4"),
                            CreatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            FieldId = new Guid("e4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 2, 19, 43, 21, 272, DateTimeKind.Utc).AddTicks(2198),
                            ValueDocumentUrl = "/docs/inspections/van-2024.pdf"
                        });
                });

            modelBuilder.Entity("ITask7.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4468f516-58c0-4a25-af81-a811fa7559e9",
                            Email = "admin@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@COMPANY.COM",
                            NormalizedUserName = "ADMIN@COMPANY.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3c2e3517-2d99-495c-a2ce-2e8740351765",
                            TwoFactorEnabled = false,
                            UserName = "admin@company.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", "Creator")
                        .WithMany("CreatedInventories")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryAccess", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Accesses")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITask7.Users.ApplicationUser", "User")
                        .WithMany("Accesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Fields")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.ItemFieldValue", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.InventoryField", "Field")
                        .WithMany("Values")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITask7.Models.Inventories.Item", "Item")
                        .WithMany("FieldValues")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("Fields");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("ITask7.Users.ApplicationUser", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("CreatedInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
