// <auto-generated />
using System;
using ITask7.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITask7.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260305172146_ItemsCreators")]
    partial class ItemsCreators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("inventories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Track laptops, monitors, peripherals, and other IT assets",
                            IsPublic = false,
                            Name = "IT Equipment",
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 2, 28, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Track stationery, printer supplies, and office consumables",
                            IsPublic = true,
                            Name = "Office Supplies",
                            UpdatedAt = new DateTime(2026, 2, 28, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 2, 23, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            Description = "Company vehicles and maintenance records",
                            IsPublic = false,
                            Name = "Vehicle Fleet",
                            UpdatedAt = new DateTime(2026, 2, 23, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789)
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryAccess", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("inventories_accesses", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DisplayInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId", "Name")
                        .IsUnique();

                    b.HasIndex("InventoryId", "SortOrder");

                    b.ToTable("inventory_fields", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Physical asset tag number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "asset_tag",
                            SortOrder = 1,
                            Title = "Asset Tag"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Manufacturer serial number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "serial_number",
                            SortOrder = 2,
                            Title = "Serial Number"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Original purchase price in USD",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "purchase_price",
                            SortOrder = 3,
                            Title = "Purchase Price"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Warranty expiration date",
                            DisplayInTable = false,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "warranty_expires",
                            SortOrder = 4,
                            Title = "Warranty Expires"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Currently assigned to employee",
                            DisplayInTable = true,
                            FieldType = "Boolean",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = true,
                            Name = "is_assigned",
                            SortOrder = 5,
                            Title = "Assigned"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Additional information",
                            DisplayInTable = false,
                            FieldType = "MultiLine",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "notes",
                            SortOrder = 6,
                            Title = "Notes"
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Upload purchase documentation",
                            DisplayInTable = false,
                            FieldType = "Document",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsRequired = false,
                            Name = "receipt",
                            SortOrder = 7,
                            Title = "Purchase Receipt"
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Name of the supply item",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "product_name",
                            SortOrder = 1,
                            Title = "Product Name"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Current stock count",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "quantity",
                            SortOrder = 2,
                            Title = "Quantity in Stock"
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Minimum stock before reorder",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = true,
                            Name = "reorder_point",
                            SortOrder = 3,
                            Title = "Reorder Point"
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Supplier contact and ordering details",
                            DisplayInTable = false,
                            FieldType = "MultiLine",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsRequired = false,
                            Name = "supplier_info",
                            SortOrder = 4,
                            Title = "Supplier Information"
                        },
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Vehicle registration number",
                            DisplayInTable = true,
                            FieldType = "SingleLine",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "license_plate",
                            SortOrder = 1,
                            Title = "License Plate"
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Odometer reading",
                            DisplayInTable = true,
                            FieldType = "Numeric",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "mileage",
                            SortOrder = 2,
                            Title = "Current Mileage"
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Current insurance status",
                            DisplayInTable = true,
                            FieldType = "Boolean",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = true,
                            Name = "insurance_active",
                            SortOrder = 3,
                            Title = "Insurance Active"
                        },
                        new
                        {
                            Id = new Guid("e4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            Description = "Annual inspection reports",
                            DisplayInTable = false,
                            FieldType = "Document",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsRequired = false,
                            Name = "inspection_docs",
                            SortOrder = 4,
                            Title = "Inspection Documents"
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomId")
                        .IsUnique();

                    b.HasIndex("InventoryId");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-LAPTOP-001",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 5, 15, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-LAPTOP-002",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 5, 15, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789)
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 4, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "IT-MON-001",
                            InventoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedAt = new DateTime(2026, 3, 4, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789)
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 2, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "SUP-A4-PAPER",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UpdatedAt = new DateTime(2026, 3, 4, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789)
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 1, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "SUP-TONER-BLK",
                            InventoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UpdatedAt = new DateTime(2026, 3, 3, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789)
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 26, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            CreatedBy = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            CustomId = "VH-001",
                            InventoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UpdatedAt = new DateTime(2026, 3, 5, 12, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789)
                        });
                });

            modelBuilder.Entity("ITask7.Models.Inventories.ItemFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("boolean");

                    b.Property<string>("ValueDocumentUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValueNumeric")
                        .HasColumnType("numeric");

                    b.Property<string>("ValueText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("ItemId", "FieldId")
                        .IsUnique();

                    b.ToTable("item_field_values", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6fd6cf9e-c13a-4f02-bf7c-a4a140d17897"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "AST-2024-001"
                        },
                        new
                        {
                            Id = new Guid("28e63424-9be7-4f72-8790-9c6ee8cb0474"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "SN123456789"
                        },
                        new
                        {
                            Id = new Guid("fe49164b-9768-4052-bb2a-a166d016e712"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueNumeric = 1299.99m
                        },
                        new
                        {
                            Id = new Guid("91d49827-64bf-41c0-9c2e-4628475f0375"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "2027-03-15"
                        },
                        new
                        {
                            Id = new Guid("95197323-f634-4664-a783-1d2e4dfea39c"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("f3663813-0590-43c9-a028-6e55fe848add"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            ItemId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "Assigned to Engineering team lead"
                        },
                        new
                        {
                            Id = new Guid("d31ef362-7c76-4f23-9008-9b4b1be11b38"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "AST-2024-002"
                        },
                        new
                        {
                            Id = new Guid("a8128395-84b5-4768-bce9-15cbc35c0a9e"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "SN987654321"
                        },
                        new
                        {
                            Id = new Guid("26507aec-617e-4610-b6f9-58d610f35908"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueNumeric = 1599.50m
                        },
                        new
                        {
                            Id = new Guid("13076fc0-6401-43d3-a29c-94ffd5ff51bb"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "2027-06-20"
                        },
                        new
                        {
                            Id = new Guid("ed6c7a21-51ae-4b8e-bbdf-f21ed5ecc05d"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueBoolean = false
                        },
                        new
                        {
                            Id = new Guid("fd3af1c5-1fff-4702-aeab-08c10399f182"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "AST-2023-045"
                        },
                        new
                        {
                            Id = new Guid("3d157648-e8dc-4876-af1c-66b4b1190076"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "DELL-SN-778899"
                        },
                        new
                        {
                            Id = new Guid("708ef12a-cc32-48b3-9a52-1565c0552490"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueNumeric = 349.00m
                        },
                        new
                        {
                            Id = new Guid("8f37d808-9fb6-4d09-bb71-91ae757a1173"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            ItemId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("4095b801-a4fa-4bb3-b35f-35d48c9bd8d7"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "A4 Copy Paper (500 sheets)"
                        },
                        new
                        {
                            Id = new Guid("dfd72a15-429b-46e8-b290-17174938ecdd"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 4, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueNumeric = 45m
                        },
                        new
                        {
                            Id = new Guid("bb2aff18-cef2-4e37-a25c-7040477ef5d4"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueNumeric = 10m
                        },
                        new
                        {
                            Id = new Guid("77f7fbcb-a7f5-406b-bb92-ac714c03fd21"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "Staples Inc. - staples.com - Account #12345"
                        },
                        new
                        {
                            Id = new Guid("e43661ad-b2a6-438f-978d-df21cef1f0a1"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "HP LaserJet Black Toner 85A"
                        },
                        new
                        {
                            Id = new Guid("47c6698b-e50d-4ce0-9856-65fa558955fb"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 3, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueNumeric = 3m
                        },
                        new
                        {
                            Id = new Guid("b056a644-8666-4da0-ac34-42a0b98b2a32"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueNumeric = 2m
                        },
                        new
                        {
                            Id = new Guid("4d8af55a-30ca-49bc-9db0-9a5ac2403ef4"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("e1111111-1111-1111-1111-111111111111"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueText = "ABC-1234"
                        },
                        new
                        {
                            Id = new Guid("c5071b87-9f64-4f86-bf7d-7c11dad0df39"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("e2222222-2222-2222-2222-222222222222"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 12, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueNumeric = 45230m
                        },
                        new
                        {
                            Id = new Guid("35a889c5-e79c-4ea5-8c1f-949613d6741d"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("e3333333-3333-3333-3333-333333333333"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueBoolean = true
                        },
                        new
                        {
                            Id = new Guid("191c7193-bd4a-4ed9-b036-f6a2a28a705d"),
                            CreatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            FieldId = new Guid("e4444444-4444-4444-4444-444444444444"),
                            ItemId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 3, 5, 17, 21, 45, 353, DateTimeKind.Utc).AddTicks(3789),
                            ValueDocumentUrl = "/docs/inspections/van-2024.pdf"
                        });
                });

            modelBuilder.Entity("ITask7.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Email"), "BTree");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Email"), new[] { "varchar_pattern_ops" });

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "99997999-7b3e-418f-9f53-38ec31c09abb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "68121b8c-c149-41e1-bedd-4c39f44cb6a4",
                            Email = "admin@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@COMPANY.COM",
                            NormalizedUserName = "ADMIN@COMPANY.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10edd645-3574-409e-bbaa-8c7c3806765d",
                            TwoFactorEnabled = false,
                            UserName = "admin@company.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", "Creator")
                        .WithMany("CreatedInventories")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryAccess", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Accesses")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITask7.Users.ApplicationUser", "User")
                        .WithMany("Accesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Fields")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", "Creator")
                        .WithMany("CreatedItems")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ITask7.Models.Inventories.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.ItemFieldValue", b =>
                {
                    b.HasOne("ITask7.Models.Inventories.InventoryField", "Field")
                        .WithMany("Values")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITask7.Models.Inventories.Item", "Item")
                        .WithMany("FieldValues")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ITask7.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Inventory", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("Fields");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.InventoryField", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("ITask7.Models.Inventories.Item", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("ITask7.Users.ApplicationUser", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("CreatedInventories");

                    b.Navigation("CreatedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
