//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITask7.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITask7.Resources.Views.Home.Index.en", typeof(Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string _new {
            get {
                return ResourceManager.GetString("new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string _private {
            get {
                return ResourceManager.GetString("private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string _public {
            get {
                return ResourceManager.GetString("public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information.
        /// </summary>
        internal static string account_information {
            get {
                return ResourceManager.GetString("account_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type.
        /// </summary>
        internal static string account_type {
            get {
                return ResourceManager.GetString("account_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available inventories.
        /// </summary>
        internal static string available_inventories {
            get {
                return ResourceManager.GetString("available_inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string company_b2b {
            get {
                return ResourceManager.GetString("company_b2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete profile.
        /// </summary>
        internal static string complete_profile {
            get {
                return ResourceManager.GetString("complete_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        internal static string contact_information {
            get {
                return ResourceManager.GetString("contact_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first inventory.
        /// </summary>
        internal static string create_first_inventory {
            get {
                return ResourceManager.GetString("create_first_inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create inventory.
        /// </summary>
        internal static string create_inventory {
            get {
                return ResourceManager.GetString("create_inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new inventory.
        /// </summary>
        internal static string create_new_inventory {
            get {
                return ResourceManager.GetString("create_new_inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter company name.
        /// </summary>
        internal static string enter_company_name {
            get {
                return ResourceManager.GetString("enter_company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter department.
        /// </summary>
        internal static string enter_department {
            get {
                return ResourceManager.GetString("enter_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description (optional).
        /// </summary>
        internal static string enter_description {
            get {
                return ResourceManager.GetString("enter_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter first name.
        /// </summary>
        internal static string enter_first_name {
            get {
                return ResourceManager.GetString("enter_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter inventory name.
        /// </summary>
        internal static string enter_inventory_name {
            get {
                return ResourceManager.GetString("enter_inventory_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter_job_title.
        /// </summary>
        internal static string enter_job_title {
            get {
                return ResourceManager.GetString("enter_job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter_last_name.
        /// </summary>
        internal static string enter_last_name {
            get {
                return ResourceManager.GetString("enter_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string gdpr_consent_text {
            get {
                return ResourceManager.GetString("gdpr_consent_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        internal static string industry {
            get {
                return ResourceManager.GetString("industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        internal static string job_title {
            get {
                return ResourceManager.GetString("job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make public.
        /// </summary>
        internal static string make_public {
            get {
                return ResourceManager.GetString("make_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        internal static string marketing_consent_label {
            get {
                return ResourceManager.GetString("marketing_consent_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My inventories .
        /// </summary>
        internal static string my_inventories {
            get {
                return ResourceManager.GetString("my_inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t own any inventories yet..
        /// </summary>
        internal static string no_owned_inventories {
            get {
                return ResourceManager.GetString("no_owned_inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No inventories have been shared with you..
        /// </summary>
        internal static string no_shared_inventories {
            get {
                return ResourceManager.GetString("no_shared_inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal account.
        /// </summary>
        internal static string personal_account {
            get {
                return ResourceManager.GetString("personal_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public inventories can be writed at by anyone with the link..
        /// </summary>
        internal static string public_inventory_tip {
            get {
                return ResourceManager.GetString("public_inventory_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save profile.
        /// </summary>
        internal static string save_profile {
            get {
                return ResourceManager.GetString("save_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select industry.
        /// </summary>
        internal static string select_industry {
            get {
                return ResourceManager.GetString("select_industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string visibility {
            get {
                return ResourceManager.GetString("visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your inventories and collaborate with your team.
        /// </summary>
        internal static string welcome_subtitle {
            get {
                return ResourceManager.GetString("welcome_subtitle", resourceCulture);
            }
        }
    }
}
